name: linc-convert-dev
channels:
  - conda-forge
dependencies:
  - python
  - ipython
  - typer
  - numpy
  - glymur
  - zarr>=3
  - nibabel
  - tifffile
  - tensorstore
  - pytest
  - ruff
  - tifffile
  - pip
  - h5py
  - scipy
  - pip:
    - cyclopts>=3.0.0
    - wkw
    - nifti-zarr
